// 支持的平台类型
export type Platform =
  | 'youtube'
  | 'tiktok'
  | 'twitter'
  | 'instagram'
  | 'douyin'
  | 'xiaohongshu'
  | 'wechat'
  | 'pornhub'
  | 'bilibili'
  | 'other'     // 其他平台（通过 yt-dlp 解析）
  | 'unknown';

// 视频格式
export interface VideoFormat {
  id: string;
  quality: string;        // e.g., "1080p", "720p", "360p"
  format: string;         // e.g., "mp4", "webm", "mkv"
  size?: number;          // 文件大小（字节）
  sizeText?: string;      // 人类可读的大小
  url: string;
  hasAudio: boolean;
  hasVideo: boolean;
  bitrate?: number;
  noWatermark?: boolean;
  codec?: string;         // e.g., "h264", "vp9", "av1"
  fps?: number;           // 帧率
}

// 字幕信息
export interface Subtitle {
  lang: string;           // 语言代码, e.g. "en", "zh-Hans"
  label: string;          // 人类可读标签, e.g. "English", "中文（简体）"
  url: string;            // 字幕文件下载 URL
  format?: string;        // 字幕格式, e.g. "srt", "vtt", "ass"
  isAutoGenerated?: boolean; // 是否为自动生成字幕
}

// 视频信息
export interface VideoInfo {
  id: string;
  platform: Platform;
  title: string;
  description?: string;
  thumbnail: string;
  duration: number;       // 秒
  durationText?: string;  // 人类可读的时长
  author?: string;
  authorAvatar?: string;
  formats: VideoFormat[];
  subtitles?: Subtitle[]; // 字幕列表
  originalUrl: string;
  parsedAt: number;       // 解析时间戳
  expiresIn?: number;     // 链接过期时间（秒）
}

// 解析结果
export interface ParseResult {
  success: boolean;
  data?: VideoInfo;
  error?: string;
}

// 下载请求
export interface DownloadRequest {
  videoUrl: string;
  audioUrl?: string;         // 音频 URL（用于合并）
  formatId?: string;         // yt-dlp 格式 ID（如 137+140）
  action?: 'download' | 'merge' | 'trim' | 'extract-audio';
  trim?: {
    start: number;
    end: number;
  };
  filename?: string;
  audioFormat?: 'mp3' | 'm4a' | 'aac' | 'wav';
  audioBitrate?: number;     // kbps
}

// API 响应
export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
}

// 平台配置
export interface PlatformConfig {
  name: string;
  domains: string[];
  color: string;
  icon: string;
  enabled: boolean;
}
